[Interface]
PrivateKey = $WIREGUARD_PRIVATE_KEY
Address = $WIREGUARD_ADDRESS
ListenPort = $WIREGUARD_PORT
MTU = 1420
PostUp = ip route add 10.0.0.0/8 dev wg0

[Peer]
PublicKey = /CoiQBGx1BM7xvz3FT7pWTD5xh0QREuaQEC1usVjjXk=
AllowedIPs = 10.0.0.0/8